"""``bf`` -- the bfdiag command-line dispatcher.

This module owns subcommand discovery for the whole ``bfdiag`` platform.
Every subpackage of ``bfdiag`` (``bfdiag.record``, and eventually
``bfdiag.trace``, ``bfdiag.invariants``, ``bfdiag.oracle`` from the other
bfdiag work streams) may define a ``cli.py`` with a
``register(subparsers) -> None`` function; this dispatcher imports each one
it finds and lets it add its own subcommands.

Discovery is defensive on purpose: the other subpackages are being built in
parallel and may not exist yet in a given checkout, or may temporarily fail
to import while under construction. A missing or broken subpackage must
never break ``bf`` for the subcommands that *do* work -- it's silently
skipped (pass ``--debug`` to see why).

Contract for ``register(subparsers)``: it should call
``subparsers.add_parser(name)`` for each subcommand it owns, and attach a
handler with ``parser.set_defaults(func=handler)`` where
``handler(args: argparse.Namespace) -> int`` returns a process exit code.
"""

from __future__ import annotations

import argparse
import importlib
import os
import pkgutil
import sys
from pathlib import Path
from types import ModuleType

import bfdiag

# -- worktree-safe checkout guard --------------------------------------------
#
# The installed `bf` console script (~/.venvs/vllm/bin/bf) is a tiny shim
# generated by pip that does `from bfdiag.cli import main`. When Python
# resolves that import, `sys.path[0]` is the *shim's own directory*
# (the venv's bin/), which contains no project code. Resolution falls
# through to the venv's pip-editable MetaPathFinder for the "blackwellm"
# package -- and that finder (see
# .../site-packages/__editable___blackwellm_0_1_0_finder.py) has the
# directory `pip install -e .` was run from HARD-CODED as the package
# source, regardless of which git worktree you actually `cd`ed into or ran
# `bf` from.
#
# Net effect without this guard: `cd <some other worktree> && bf ...`
# silently imports `bfdiag`/`runtime`/`server`/`benchmarks` from a
# DIFFERENT checkout, with no error and no warning -- run records, `.bfdiag`
# state, and even the daemon subprocess `bf daemon start` launches
# (`bfdiag/daemon/cli.py::_repo_root`, `bfdiag/daemon/server.py::bfdiag_dir`
# all derive "repo root" from `Path(__file__).resolve().parents[N]`, i.e.
# from wherever the currently-loaded module physically lives) all come from
# the wrong checkout. Confirmed empirically 2026-08-01/08-02, see
# notes/2026-08-01-sparkinfer-patch-recovery-and-repro.md §7.1 and
# docs/diagnostics-guide.md.
#
# The fix has to live here, at the top of `main()`, because by the time any
# *other* bfdiag code could run a check, the (possibly wrong) `bfdiag`
# package is already the one bound in `sys.modules` -- imports are cached,
# so no later `sys.path` change can retroactively redirect them. `main()`
# itself is the first thing the installed shim calls, and nothing with
# side effects has run yet (importing `bfdiag`/`bfdiag.cli` only defines
# functions), so it is still safe to detect a mismatch here and, if found,
# re-exec the whole process through `python -m bfdiag.cli` -- which puts
# the current directory (not the shim's directory) at `sys.path[0]`, so the
# stdlib PathFinder resolves the LOCAL checkout before the pip-editable
# finder (appended at the very end of `sys.meta_path`) is ever consulted.
_RELAUNCH_GUARD_ENV = "_BFDIAG_CLI_CHECKOUT_VERIFIED"


def _find_repo_root(start: Path) -> Path | None:
    """Walk up from *start* for the nearest ancestor that looks like a
    ``blackwellm`` checkout (has both ``bfdiag/__init__.py`` and a
    ``pyproject.toml`` naming this package). Returns ``None`` if ``bf`` was
    invoked from somewhere outside any such checkout -- in that case there
    is nothing to correct against, so the caller should do nothing."""
    current = start.resolve()
    for candidate in (current, *current.parents):
        init_py = candidate / "bfdiag" / "__init__.py"
        pyproject = candidate / "pyproject.toml"
        if not init_py.is_file() or not pyproject.is_file():
            continue
        try:
            header = pyproject.read_text()[:2000]
        except OSError:
            continue
        if 'name = "blackwellm"' in header:
            return candidate
    return None


def _loaded_repo_root() -> Path:
    """Root of the checkout the *currently imported* ``bfdiag`` package was
    actually loaded from (``bfdiag/__init__.py`` -> repo root is one parent
    up)."""
    return Path(bfdiag.__file__).resolve().parent.parent


def _ensure_correct_checkout(cwd: Path | None = None) -> None:
    """Refuse to silently run diagnostics against the wrong checkout.

    If the current directory is inside a recognizable ``blackwellm``
    checkout that is *not* the one ``bfdiag`` actually resolved to, this
    either transparently relaunches the process against the right one (the
    common case: the pip-editable trap described above) or, if a relaunch
    already happened once in this process tree and the mismatch persists
    (which should not happen), fails loudly instead of proceeding on
    code from the wrong repo.

    ``cwd`` defaults to the real current directory; tests pass an explicit
    value instead of monkeypatching ``Path.cwd``.
    """
    wanted_root = _find_repo_root(cwd if cwd is not None else Path.cwd())
    if wanted_root is None:
        return  # cwd isn't inside any recognizable checkout -- nothing to fix
    loaded_root = _loaded_repo_root()
    if wanted_root == loaded_root:
        return  # already correct

    if os.environ.get(_RELAUNCH_GUARD_ENV) == "1":
        raise SystemExit(
            f"bf: refusing to continue -- bfdiag was loaded from {loaded_root} "
            f"but the current directory is inside {wanted_root}, and a "
            "relaunch already tried to fix this once in this process tree "
            "and failed. This should not happen; see 'bf and worktrees' in "
            "docs/diagnostics-guide.md."
        )

    print(
        f"bf: bfdiag resolved to {loaded_root} (via the venv's pip-editable "
        f"finder) but the current directory is inside {wanted_root} -- "
        "relaunching against the correct checkout so this run doesn't "
        "silently test the wrong code. See 'bf and worktrees' in "
        "docs/diagnostics-guide.md.",
        file=sys.stderr,
    )
    new_env = dict(os.environ)
    new_env[_RELAUNCH_GUARD_ENV] = "1"
    new_env["PYTHONPATH"] = str(wanted_root) + (
        os.pathsep + new_env["PYTHONPATH"] if new_env.get("PYTHONPATH") else ""
    )
    _relaunch([sys.executable, "-m", "bfdiag.cli", *sys.argv[1:]], new_env)


def _relaunch(argv: list[str], env: dict[str, str]) -> None:
    """``os.execve`` in its own function so tests can monkeypatch it instead
    of actually replacing the test process."""
    os.execve(argv[0], argv, env)  # noqa: S606 - intentional process replacement


def _iter_subpackages() -> list[str]:
    return sorted(name for _, name, is_pkg in pkgutil.iter_modules(bfdiag.__path__) if is_pkg)


def _candidate_module_names() -> list[str]:
    """Registrar modules to try, across both platform packages.

    ``bfdiag`` groups its subcommands into subpackages, each with a
    ``cli`` module (``bfdiag.record.cli``, ``bfdiag.trace.cli``, ...).
    ``bfprobe`` (the probe system) is flat instead, so its registrars are
    top-level modules named ``cli`` or ``*_cli`` (``bfprobe.cli``,
    ``bfprobe.scan_cli``). Both shapes land on the same
    ``register(subparsers)`` contract, so ``bf`` exposes them as one CLI.
    """
    names = [f"bfdiag.{sub}.cli" for sub in _iter_subpackages()]
    try:
        import bfprobe
    except Exception:  # noqa: BLE001 - bfprobe is optional at runtime
        return names
    names += sorted(
        f"bfprobe.{name}"
        for _, name, is_pkg in pkgutil.iter_modules(bfprobe.__path__)
        if not is_pkg and (name == "cli" or name.endswith("_cli"))
    )
    return names


def _discover_registrars(debug: bool) -> list[ModuleType]:
    registrars: list[ModuleType] = []
    for module_name in _candidate_module_names():
        try:
            module = importlib.import_module(module_name)
        except Exception as exc:  # noqa: BLE001 - sibling subpackages may not exist yet
            if debug:
                print(f"bf --debug: skipping {module_name}: {exc!r}", file=sys.stderr)
            continue
        register = getattr(module, "register", None)
        if not callable(register):
            if debug:
                print(f"bf --debug: {module_name} has no register(subparsers)", file=sys.stderr)
            continue
        registrars.append(module)
    return registrars


def build_parser(debug: bool = False) -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="bf", description="BlackForge diagnostics (bfdiag) command line"
    )
    parser.add_argument(
        "--debug", action="store_true", help="print subcommand-discovery diagnostics to stderr"
    )
    subparsers = parser.add_subparsers(dest="command")
    for module in _discover_registrars(debug):
        module.register(subparsers)
    return parser


def main(argv: list[str] | None = None) -> int:
    _ensure_correct_checkout()
    argv = sys.argv[1:] if argv is None else list(argv)
    debug = "--debug" in argv
    parser = build_parser(debug=debug)
    args = parser.parse_args(argv)

    handler = getattr(args, "func", None)
    if handler is None:
        parser.print_help()
        return 1
    return handler(args) or 0


if __name__ == "__main__":
    sys.exit(main())
